### ISSUE TITLE
This database has local access protection

### ISSUE THREAD

**Issue by mihaiandreicut** [DominoMFA/MFA#1]
Hello,
Please remove local access protection. 
![image](https://user-images.githubusercontent.com/6103377/149522910-867fab38-e219-4b48-9815-90ad05bb7cd0.png)
Thank you !

**Comment by dpastov** [comment]
@mihaiandreicut thanks for an creating a ticket. It should be fixed as of now.

**Comment by dpastov** [comment]
I will close the ticket but otherwise let me know if it still bugging you.
